### ISSUE TITLE
Can't set dice on sub-trait

### ISSUE THREAD

**Issue by bblonski** [Secular12/cortexprime#20]
Affected module version: 0.0.3
Foundry VTT version: 0.8.8

I tried to create skill specializations by creating a Trait set with dice, sub-traits, and sub-traits have dice. When I add a custom skill trait, I can add the specialization sub-trait, but cannot change it's dice size. I see the following error in the console logs.

```
Uncaught (in promise) TypeError: Cannot read property 'value' of undefined
    at CortexPrimeActorSheet._onDieChange (actor-sheet.js:284)
    at HTMLSelectElement.dispatch (jquery.min.js:2)
    at HTMLSelectElement.v.handle (jquery.min.js:2)
```

**Comment by Secular12** [comment]
Thanks! I actually stumbled on this too. Pushing a hot fix for it shortly.

**Comment by Secular12** [comment]
Released
