### ISSUE TITLE
Modifying a copy of a character sheet may cause the copy not to be saved properly

### ISSUE THREAD

**Issue by kunxin-chor** [Secular12/cortexprime#26]
Original copy:

![image](https://user-images.githubusercontent.com/14900791/127731556-036fb425-e0d1-49c4-b0a0-1ee551cbb453.png)

After making changes and closing the copied sheet (I copied and pasted into the first trait of the Distinction)

![image](https://user-images.githubusercontent.com/14900791/127731582-4cb364f0-7661-420d-9f30-ddc641e62ce4.png)

**Comment by kunxin-chor** [comment]
Maybe not a bug but more of an UI issue; each sheet remembered the state it was at when it is closed so when I reopened the sheet it looks like every other traits has disappeared.

**Comment by Secular12** [comment]
Thanks @kunxin-chor I will look into the issue. Nearing another release here, mostly bug fixes, and I will fit this into the release.

**Comment by Secular12** [comment]
@kunxin-chor it looks as though it may potentially be an issue when closing the sheet before Foundry updates the data? Steps I did to reproduce the issue:

1. Copy a actor
2. Open up copied actor
3. Edit a trait in a trait set
4. close the sheet without clicking "back"
5. reopen the sheet

At which point it doesn't shot the update made

If, in step 4, if I clicked back before closing it, it seems to prevent the issue, i.e. the update can be seen.

This may be a foundry issue itself, but I will look into seeing if I can make sure it is updated upon closing. Furthermore, if I am not fully understanding the issue you are seeing, please let me know.

**Comment by Secular12** [comment]
Strange... now I can no longer reproduce the issue like I thought I was... could you, by chance, provide step by step what you did you make this issue occur? One that I can use to reproduce each time.

**Comment by Secular12** [comment]
Closing at I cannot replicate the issue
