### ISSUE TITLE
Dice result symbol is the same as dice type sybol

### ISSUE THREAD

**Issue by ashleytowner** [Secular12/cortexprime#53]
In the cortex prime rulebook, it describes a difference in style for dice _results_ and dice _types_, where types are solid pink with a white number in the middle, and results are solid white with a pink border a black number within. (Then solid green with white text for effect dice)
![image](https://user-images.githubusercontent.com/13824257/166098851-b572e087-5f9f-492e-b90f-6d18125f5e51.png)

The rolls in foundry using this module show dice results and dice types the same way (solid pink)

![image](https://user-images.githubusercontent.com/13824257/166098798-d01938d2-e83e-4518-b885-fd17401551fc.png)

This should be changed to reflect the styles used in the core rule system.

**Comment by Secular12** [comment]
This should get addressed in the next big Themes update!

**Comment by Secular12** [comment]
Resolved
