### ISSUE TITLE
Feature Request: Scale Dice

### ISSUE THREAD

**Issue by GhostwheelX** [Secular12/cortexprime#76]
Might it be possible to implement scale dice in the die roller? (Detailed in page 99 of handbook.)

**Comment by Secular12** [comment]
> Might it be possible to implement scale dice in the die roller? (Detailed in page 99 of handbook.)

This is something that can be looked into. As of right now it is possible to add 3 dice to your total, Just use Roll & Select and use the "+" button under total in the popup, after selecting dice you want to add, to add as many dice as desired into the total.
