### ISSUE TITLE
Traits getting mangled when rearranging trait groups in the config.

### ISSUE THREAD

**Issue by olavmueller** [Secular12/cortexprime#79]
I played around with the Actor Settings a bit in order to get a nice character sheet for ToX. After adding about 6 Trait Sets and filling out most of them with presets (attributes, values, three different distinctions) I tried to rearrange the sets in order to get a better visual on my sheets. Unfortunately this mangled up my groups. It seems that only parts of the trait sets were copied to the new position and this destroyed my test character twice. Has this been reported or should I try to reproduce this (again) and make some screenshots? 

Foundry 9.269, CP 0.2.7, no active mods.

**Comment by Secular12** [comment]
I do apologize for the late reply. However, I am aware of this issue, it is actually a css issue in how the browser decides to arrange columns. I am currently overhauling the entire system and part of that overhaul will include explicitly arranging the trait sets in specific columns.
