### ISSUE TITLE
Feature request: update system for Foundry 11

### ISSUE THREAD

**Issue by mateoayat** [Secular12/cortexprime#84]
I've been running Cortex games on Foundry for over 3 years now with this wonderful system, but Forge recently updated their recommended stable release from Foundry 10 to Foundry 11. As I also run other systems, I decided to update, as I'm sure other people did, but was disenhearted to find out this system is incompatible with Foundry 11 at the moment.

Would it be possible to update the system to run with Foundry 11?

**Comment by Secular12** [comment]
Done. I thought I did this earlier but I forgot to update the system.json file to indicate it works for v11

**Comment by mateoayat** [comment]
Thank you so much! Our game is up and running again!
